implement capture meta
teragrep/cfe_18 pull request #68
Opened 2024-06-13 09:35 UTC by Nefarious46

2024-06-13 09:59 UTC, kortemik requested changes

2024-06-13 09:59 UTC, kortemik commented on src/main/resources/db/migration/R__Procedure_Retrieve_Capture_meta.sql
> +               a.app                as          application,
this is bit extra?

2024-06-13 09:59 UTC, kortemik commented on src/main/resources/com/teragrep/cfe18/CaptureMetaMapper.xml
> +        <result property="application" column="application"/>
this is bit extra?

2024-06-13 09:59 UTC, kortemik commented on src/main/resources/db/migration/R__Procedure_add_capture_meta.sql
> +    -- return given application name and capture_id as signal
capture_id is enough?

2024-06-13 12:03 UTC, kortemik commented on src/main/resources/db/migration/R__Procedure_Retrieve_Capture_meta.sql
> +               a.app                as          application,
only application should have been removed but capture_id left.

2024-06-13 12:03 UTC, kortemik requested changes
retain capture_id instead of removing both

2024-06-17 08:13 UTC, StrongestNumber9 requested changes
No strong opinions about the code, some notes about tests

2024-06-17 08:13 UTC, StrongestNumber9 commented on src/test/java/com/teragrep/cfe18/controllerTests/CaptureMetaControllerTest.java
> +    public void testAddCaptureMeta() throws Exception{
Don't throw exceptions in tests

2024-06-17 08:13 UTC, StrongestNumber9 commented on src/test/java/com/teragrep/cfe18/controllerTests/CaptureMetaControllerTest.java
> +    public void testRetrieveCaptureMeta() throws Exception {
Don't throw exceptions in tests

2024-06-17 08:13 UTC, StrongestNumber9 commented on src/test/java/com/teragrep/cfe18/controllerTests/CaptureMetaControllerTest.java
> +        String json = gson.toJson(expected);
Theres no real self-contained guarantee that captureMeta works correctly -> can cause expected to be `{}` -> the responseGet can also return invalid values but this test still passes. Either build json from well known string or also test the captureMeta contents.

2024-06-17 08:13 UTC, StrongestNumber9 commented on src/test/java/com/teragrep/cfe18/controllerTests/CaptureMetaControllerTest.java
> +    public void testNoCaptureForInsertingMeta() throws Exception {
Don't throw exceptions in tests

2024-06-17 08:13 UTC, StrongestNumber9 commented on src/test/java/com/teragrep/cfe18/controllerTests/CaptureMetaControllerTest.java
> +    public void testNoMetaForCapture() throws Exception {
Don't throw exceptions in tests

2024-06-25 08:40 UTC, kortemik requested changes

2024-06-25 08:40 UTC, kortemik commented on src/main/java/com/teragrep/cfe18/handlers/CaptureMetaController.java
> +            jsonErr.put("id", 0);
why id is set to 0 instead of not present on error

2024-06-25 08:40 UTC, kortemik commented on src/main/java/com/teragrep/cfe18/handlers/CaptureMetaController.java
> +        jsonErr.put("id", 0);
why id is defaulting to 0?

2024-06-25 08:40 UTC, kortemik commented on src/main/java/com/teragrep/cfe18/handlers/CaptureMetaController.java
> +            jsonErr.put("id", 0);
why id is set to 0 instead of not present on error

2024-06-25 08:40 UTC, kortemik commented on src/main/resources/db/migration/R__Procedure_add_capture_meta.sql
> +    -- check if application exists for metadata
legacy comment

2024-06-25 08:40 UTC, kortemik commented on src/main/resources/db/migration/R__Procedure_add_capture_meta.sql
> +    -- return given application name and capture_id as signal
is last insert id available from @ id that might be ok to add

2024-07-11 12:20 UTC, StrongestNumber9 commented on src/test/java/com/teragrep/cfe18/controllerTests/CaptureMetaControllerTest.java
> +    public void testAddCaptureMeta() throws Exception{
You can capture them using tools provided by junit, examples are in testing procedure doc

2024-08-06 11:57 UTC, kortemik approved these changes

2024-08-06 12:01 UTC, StrongestNumber9 approved these changes

2024-08-06 12:02 UTC, merged